// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A supplement recommendation AI agent.
 *
 * - recommendSupplements - A function that handles the supplement recommendation process.
 * - SupplementRecommendationInput - The input type for the recommendSupplements function.
 * - SupplementRecommendationOutput - The return type for the recommendSupplements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SupplementRecommendationInputSchema = z.object({
  fitnessGoals: z
    .string()
    .describe('The fitness goals of the user, e.g., build muscle, lose weight, increase endurance.'),
  dietaryRestrictions: z
    .string()
    .describe('The dietary restrictions of the user, e.g., vegetarian, vegan, gluten-free.'),
});
export type SupplementRecommendationInput = z.infer<
  typeof SupplementRecommendationInputSchema
>;

const SupplementRecommendationOutputSchema = z.object({
  recommendations: z
    .string()
    .describe(
      'A list of supplement recommendations based on the fitness goals and dietary restrictions of the user.'
    ),
  dosageInstructions: z
    .string()
    .describe('Dosage instructions for each recommended supplement.'),
  supplementPairings: z
    .string()
    .describe(
      'Recommended supplement pairings to maximize effectiveness and achieve fitness goals.'
    ),
});
export type SupplementRecommendationOutput = z.infer<
  typeof SupplementRecommendationOutputSchema
>;

export async function recommendSupplements(
  input: SupplementRecommendationInput
): Promise<SupplementRecommendationOutput> {
  return recommendSupplementsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'supplementRecommendationPrompt',
  input: {schema: SupplementRecommendationInputSchema},
  output: {schema: SupplementRecommendationOutputSchema},
  prompt: `You are an expert in sports nutrition, skilled at recommending supplements based on fitness goals and dietary restrictions.

  Based on the following fitness goals and dietary restrictions, provide supplement recommendations, dosage instructions, and supplement pairings.

  Fitness Goals: {{{fitnessGoals}}}
  Dietary Restrictions: {{{dietaryRestrictions}}}

  Ensure the recommendations align with the user's goals and restrictions. Provide concise dosage instructions and suggest effective supplement pairings to maximize results.
  `,
});

const recommendSupplementsFlow = ai.defineFlow(
  {
    name: 'recommendSupplementsFlow',
    inputSchema: SupplementRecommendationInputSchema,
    outputSchema: SupplementRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
